bluerov2_0: # investigator1
  planner:
    configurations:
      max_vel:  1.0
      setpoint_thresh: 1.5

    # Actions in NED
    action0: # waypoint
      point: [-10,-10,2]
    action1:
      point: [-10,-15,2]
    action2:
      point: [-15,-15,2]
    action3:
      point: [-15,-10,2]
      repeat: 0 # send us back to action0
